ARG NODE_VERSION=10.15.1
FROM node:${NODE_VERSION}-alpine

USER root

# CHANGE SOURCE && apk upgrade
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories \
    && apk update \
    && apk upgrade \
    && apk add --no-cache openssl \
    && apk add --no-cache bash \
    && npm config set registry https://registry.npm.taobao.org

